'use strict';
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const icons={folder:'<path d="M3 7V5a2 2 0 0 1 2-2h5l2 3h7a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7Z"/><path d="M3 8h18M8 13h8m-8 4h5"/>',rename:'<path d="m4 16-1 5 5-1L20 8l-4-4L4 16Z"/><path d="m14 6 4 4M13 20h8"/>',image:'<rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8" cy="8" r="1.5"/><path d="m3 16 5-5 4 4 4-6 5 7"/>',cutout:'<path stroke-dasharray="3 3" d="M3 9V3h6m6 0h6v6m0 6v6h-6m-6 0H3v-6"/><path d="M8 17v-2a4 4 0 0 1 8 0v2M12 12a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/>',repair:'<path d="m14 3 7 7-9 11H5l-4-4L14 3Z"/><path d="m6 12 7 7m-1 2h10"/>',id:'<rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="12" cy="9" r="3"/><path d="M6 20v-2a6 6 0 0 1 12 0v2"/>',pdf:'<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8l-6-6Z"/><path d="M14 2v6h6M8 12h8m-8 4h5"/>',convert:'<path d="M3 7h16l-4-4M21 17H5l4 4"/><path d="M19 7v5M5 17v-5"/>',video:'<rect x="3" y="5" width="13" height="14" rx="3"/><path d="m16 10 5-4v12l-5-4"/>',audio:'<path d="M3 10v4m4-7v10m5-14v18m5-14v10m4-7v4"/>',ocr:'<path d="M3 8V3h5m8 0h5v5m0 8v5h-5m-8 0H3v-5M7 8h10m-10 4h10m-10 4h7"/>',tasks:'<rect x="5" y="4" width="14" height="18" rx="2"/><rect x="9" y="2" width="6" height="4" rx="1"/><path d="m8 11 1 1 2-2m2 1h3m-8 6h8"/>'};
function icon(name){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.image}</svg>`}
const tools=[
{id:'folder',name:'文件整理',cat:'文件',desc:'按类型归类，预览目标目录，再复制或移动。',keywords:'文件夹 分类 归档 复制 移动',steps:['添加源文件夹，选择是否包含子文件夹。','设置目标位置及复制 / 移动方式。','生成目录树预览，检查分类、同名编号后执行。'],boundary:'按扩展名分为七类，默认复制。移动改变路径；撤销需校验，文件发生变化时可能无法恢复。'},
{id:'rename',name:'批量改名',cat:'文件',desc:'前缀、后缀、查找替换和序号命名。',keywords:'重命名 名称 序号',steps:['选择文件，设置改名规则。','核对原文件名与新文件名预览。','执行并查看逐项结果，需要时撤销上次操作。'],boundary:'直接修改原文件名。执行与撤销前会校验文件状态，不提供跨崩溃的完整事务恢复。'},
{id:'image',name:'图片处理',cat:'图像',desc:'压缩、调整尺寸，批量输出常用格式。',keywords:'压缩 尺寸 JPG PNG HEIC 大小',steps:['导入图片或图片文件夹。','选择质量、尺寸模式和输出格式，查看预估。','批量处理，核对实际结果并保存到目标位置。'],boundary:'转换与重编码可能增加体积。输出为 8-bit sRGB，特殊色彩和原始元数据不保证保留。'},
{id:'cutout',name:'自动抠图',cat:'图像',desc:'提取前景主体，预览透明背景并导出 PNG。',keywords:'背景 透明 主体 PNG',steps:['导入一张静态图片。','运行自动抠图，在原图与结果间检查边缘。','必要时框选清除残留背景，保存透明 PNG。'],boundary:'自动提取系统识别到的前景。复杂背景与透明物体需要检查；目前没有画笔涂选或逐主体选择。'},
{id:'repair',name:'图片去水印',cat:'图像',desc:'框选局部区域，用周边或取样背景修补。',keywords:'修补 去除 取样 水印',steps:['导入图片，在预览中框选需要修补的区域。','选择周边插值，或从干净背景取样并调整羽化。','检查效果，可撤销或恢复原图，再另存输出。'],boundary:'适合简单背景，无法保证恢复被水印遮住的真实细节。处理自己的图片或已获授权的素材。'},
{id:'id',name:'证件照',cat:'图像',desc:'尺寸、换底、构图，以及整页打印排版。',keywords:'一寸 二寸 蓝底 白底 红底 A4 打印 相纸',steps:['导入人像，选择常用或自定义证件照规格。','调整构图和底色，检查发丝、眼镜及衣服边缘。','保存单张照片，或选择纸张预览并导出排版 PDF。'],boundary:'预设规格不代表满足所有机构的审核要求。打印时选择“实际大小 / 100%”，排版物理成品仍需核对。'},
{id:'pdf',name:'PDF 工具',cat:'文档',desc:'合并、拆分、加密、水印和基础转换。',keywords:'总页数 页码 预览 密码 分页 文档',steps:['选择工具并导入 PDF。','拆分时查看总页数、逐页预览，设置有效页码范围。','执行并核对每项结果，导出文件；失败项可重试。'],boundary:'复杂 Word / PDF 版式不保证完整重建。加密和权限效果依赖阅读器，处理前确认源文件可读取。'},
{id:'ocr',name:'OCR 文字识别',cat:'文档',desc:'逐图提取文字，编辑、复制或分别导出。',keywords:'扫描 识字 翻译 TXT RTF 图片 文字',steps:['导入单张、多张图片或 PDF，选择识别语言。','运行识别，每张图片在自己的结果卡片中显示。','对照原图校对，复制或导出 TXT / RTF。'],boundary:'识别效果依赖原图清晰度和系统模型。复杂表格、多栏和手写文字需校对；翻译语言包可能需联网下载。'},
{id:'convert',name:'格式转换',cat:'图像',desc:'在系统支持的常用图片格式之间转换。',keywords:'JPG PNG HEIC TIFF BMP 格式',steps:['导入待转换的图片。','选择系统支持的目标格式。','开始批处理并查看任务结果，然后保存。'],boundary:'可用格式依赖系统编码器。动态图片与多页 TIFF 不是普通静态图片转换的适用对象。'},
{id:'video',name:'视频压缩',cat:'音视频',desc:'调整输出参数，重新编码日常视频素材。',keywords:'MP4 码率 分辨率 质量',steps:['选择本地视频文件。','设置输出参数并开始处理。','检查成品画质、文件大小与播放效果后保存。'],boundary:'重新编码不保证体积一定变小。HDR、多轨、字幕及全部元数据不保证保留；没有视频去水印或链接下载功能。'},
{id:'audio',name:'音视频转换',cat:'音视频',desc:'常用媒体转换，配合系统本机语音能力。',keywords:'音频 MP3 M4A WAV 提取 语音 字幕',steps:['选择媒体文件和当前可用的转换方式。','配置输出参数，开始本机处理。','查看结果并导出，再核对播放或文字内容。'],boundary:'编解码与语音能力依赖系统和设备，受保护或罕见编码可能不支持。语音语言模型可能需要下载。'},
{id:'tasks',name:'任务中心',cat:'文件',desc:'查看图片批处理队列、进度及处理结果。',keywords:'重试 取消 批量 历史 进度 队列',steps:['从图片处理或格式转换开始批量任务。','进入任务中心查看等待、执行和逐文件结果。','按需要停止、重试未完成项，保存成功结果。'],boundary:'目前覆盖图片处理及图片格式转换；不包括所有工具，也不提供跨重启续传或真正暂停。'}];
let filter='全部',query='';const categories=['全部','文件','图像','文档','音视频'];
$('#filters').innerHTML=categories.map(c=>`<button class="filter ${c===filter?'active':''}" data-cat="${c}" aria-pressed="${c===filter}">${c}</button>`).join('');
function renderTools(){const shown=tools.filter(t=>(filter==='全部'||t.cat===filter)&&`${t.name}${t.desc}${t.keywords}`.toLowerCase().includes(query));$('#tool-grid').innerHTML=shown.map(t=>`<button class="tool-card" data-tool="${t.id}" aria-label="查看${t.name}操作指南">${icon(t.id)}<h3>${t.name}</h3><p>${t.desc}</p><span>${t.cat}工具 <b>↗</b></span></button>`).join('');$('#empty-search').hidden=!!shown.length}
renderTools();$('#filters').addEventListener('click',e=>{const b=e.target.closest('[data-cat]');if(!b)return;filter=b.dataset.cat;$$('[data-cat]').forEach(n=>{n.classList.toggle('active',n===b);n.setAttribute('aria-pressed',n===b)});renderTools()});$('#tool-search').addEventListener('input',e=>{query=e.target.value.trim().toLowerCase();renderTools()});
const dialog=$('#tool-dialog');$('#tool-grid').addEventListener('click',e=>{const b=e.target.closest('[data-tool]');if(!b)return;const t=tools.find(t=>t.id===b.dataset.tool);$('#dialog-content').innerHTML=`${icon(t.id)}<h2>${t.name}</h2><p>${t.desc}</p><ol>${t.steps.map(s=>`<li>${s}</li>`).join('')}</ol><p class="boundary">适用范围：${t.boundary}</p><a class="button dark small" href="#download" id="dialog-download">获取桌面软件 ↗</a>`;dialog.showModal();$('#dialog-download').addEventListener('click',()=>dialog.close())});$('#close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),2600)}
try{if(localStorage.getItem('ruitu-theme')==='dark')document.body.classList.add('dark-mode')}catch{}
function themeLabel(){$('#theme').setAttribute('aria-label',document.body.classList.contains('dark-mode')?'切换浅色模式':'切换深色模式')};themeLabel();$('#theme').addEventListener('click',()=>{document.body.classList.toggle('dark-mode');themeLabel();try{localStorage.setItem('ruitu-theme',document.body.classList.contains('dark-mode')?'dark':'light')}catch{}});
$('.menu-toggle').addEventListener('click',e=>{const open=$('.header nav').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',open)});$$('.header nav a').forEach(a=>a.addEventListener('click',()=>{$('.header nav').classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false')}));document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!dialog.open){e.preventDefault();$('#tools').scrollIntoView();$('#tool-search').focus()}});
const demos=[{id:'folder',name:'文件整理'},{id:'image',name:'图片处理'},{id:'pdf',name:'PDF 拆分'},{id:'ocr',name:'OCR 识别'},{id:'id',name:'证件照'}];let activeDemo='folder',demoTimer=null,pdfPage=1;
$('#demo-tabs').innerHTML=demos.map((d,i)=>`<button class="demo-tab ${i===0?'active':''}" id="tab-${d.id}" data-demo="${d.id}" role="tab" aria-selected="${i===0}" aria-controls="demo-area" tabindex="${i===0?0:-1}">${icon(d.id)}${d.name}</button>`).join('');
function demoHead(name,sub){return `<div class="demo-head"><div><h3>${name}</h3><p>${sub}</p></div><span class="badge">示例演示</span></div>`}
function renderDemo(){clearTimeout(demoTimer);const area=$('#demo-area');area.setAttribute('aria-labelledby',`tab-${activeDemo}`);pdfPage=1;
if(activeDemo==='folder'){area.innerHTML=demoHead('把文件放到对的位置','先看分类和去向，再执行整理。')+`<div class="demo-card"><div class="demo-toolbar"><strong>整理结果 /</strong><span class="badge">默认复制 · 6 个示例文件</span></div><div class="tree"><details class="tree-group" open><summary>▱ 图片 <em>2</em></summary><p>春日照片.jpg<small>来源：桌面 / 相册</small></p><p>产品封面.png<small>来源：下载 / 项目</small></p></details><details class="tree-group" open><summary>▱ 文档 <em>2</em></summary><p>项目方案.pdf<small>来源：桌面 / 项目</small></p><p>会议记录.txt<small>来源：下载</small></p></details><details class="tree-group" open><summary>▱ 音频 <em>2</em></summary><p>访谈录音.m4a<small>来源：桌面</small></p><p>背景音乐.wav<small>来源：下载 / 音乐</small></p></details></div></div><div class="demo-footer"><span id="demo-feedback">预览：6 个文件将复制到 3 个分类目录</span><button class="button dark small" id="demo-run">模拟整理 <span>→</span></button></div><p class="demo-note">点击分类目录可展开 / 收起。此处不执行真实文件操作。</p>`;$('#demo-run').addEventListener('click',e=>{const b=e.currentTarget;b.disabled=true;b.textContent='正在演示…';$('#demo-feedback').textContent='示例进度：正在归类文件';demoTimer=setTimeout(()=>{if(activeDemo!=='folder')return;$('#demo-feedback').textContent='演示完成：6 个成功 · 0 个失败 · 源文件保留';$('#demo-feedback').classList.add('demo-feedback');b.textContent='重新演示 ↻';b.disabled=false},750)})}
if(activeDemo==='image'){area.innerHTML=demoHead('每一张，都有合适的大小','拖动质量滑块，观察示例体积变化。')+`<div class="demo-card"><div class="demo-toolbar"><strong>春日照片.jpg</strong><span class="badge">2400 × 1600 px</span></div><label class="demo-toolbar" for="demo-quality">输出质量 <strong id="demo-quality-label">75%</strong></label><input class="demo-slider" id="demo-quality" type="range" min="20" max="95" value="75"><div class="size-comparison"><div><small>原始大小</small><strong>3.8 MB</strong></div><span>→</span><div><small>示例输出</small><strong id="demo-size">1.7 MB</strong></div><span class="saving" id="demo-saving">减少 55%</span></div></div><p class="demo-note">这里是示意数值，不是实际编码预估。真实压缩效果取决于原图和输出设置。</p><div class="demo-footer"><span>想看看自己的图片会怎样？</span><a href="#browser-tool" class="button dark small">试试真实图片 ↗</a></div>`;$('#demo-quality').addEventListener('input',e=>{const q=Number(e.target.value),size=.25+3.55*Math.pow(q/100,2.9);$('#demo-quality-label').textContent=q+'%';$('#demo-size').textContent=size.toFixed(1)+' MB';$('#demo-saving').textContent='减少 '+Math.round((1-size/3.8)*100)+'%'})}
if(activeDemo==='pdf'){area.innerHTML=demoHead('拆分之前，先看清楚','查看总页数与范围，知道每一页去往哪里。')+`<div class="demo-card demo-pdf"><div class="paper"><h4>项目方案<br><span id="paper-page">01</span></h4><div class="paper-lines"></div><p>示例页面 · 共 8 页</p></div><div class="pdf-controls"><div class="demo-toolbar"><strong>项目方案.pdf</strong><span class="badge">总计 8 页</span></div><label for="page-range">输出范围（逗号分组）</label><input id="page-range" value="1-3, 5-7" placeholder="1-3, 5-7"><p id="range-status" class="demo-note"></p><div class="page-buttons"><button class="demo-button" id="previous-page" aria-label="预览上一页">←</button><span id="page-index">1 / 8</span><button class="demo-button" id="next-page" aria-label="预览下一页">→</button></div></div></div><p class="demo-note">更改范围查看校验结果。预览内容为示例，不是实际 PDF。</p>`;const update=()=>{const groups=parseRange($('#page-range').value,8);$('#range-status').textContent=groups.error||`预计 ${groups.ranges.length} 个文件 · ${groups.count} 页 · 当前页${groups.ranges.some(r=>pdfPage>=r[0]&&pdfPage<=r[1])?'包含':'不包含'}在范围内`;$('#range-status').style.color=groups.error?'#b76850':'';$('#paper-page').textContent=String(pdfPage).padStart(2,'0');$('#page-index').textContent=pdfPage+' / 8';$('#previous-page').disabled=pdfPage===1;$('#next-page').disabled=pdfPage===8};$('#page-range').addEventListener('input',update);$('#previous-page').addEventListener('click',()=>{pdfPage=Math.max(1,pdfPage-1);update()});$('#next-page').addEventListener('click',()=>{pdfPage=Math.min(8,pdfPage+1);update()});update()}
if(activeDemo==='ocr'){area.innerHTML=demoHead('一张图片，一个结果区域','来源清楚，文字可以分别编辑和复制。')+`<div class="ocr-demo"><article class="ocr-card"><header>${icon('image')}会议记录.png</header><textarea aria-label="会议记录示例文字">周一项目会议\n1. 确认设计方向\n2. 周三完成初稿\n3. 周五进行反馈</textarea><button class="demo-button copy-demo">复制这张的文字</button></article><article class="ocr-card"><header>${icon('image')}旅行备忘.jpg</header><textarea aria-label="旅行备忘示例文字">周末出行清单\n相机、充电器、雨伞\n别忘了看天气。</textarea><button class="demo-button copy-demo">复制这张的文字</button></article></div><p class="demo-note">以上为预填示例文字，网页没有执行 OCR。可直接编辑，点击按钮复制当前内容。</p>`;$$('.copy-demo',area).forEach(b=>b.addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('textarea',b.closest('article')).value);toast('已复制这张图片对应的文字')}catch{toast('浏览器未允许复制，请选中文字后复制')}}))}
if(activeDemo==='id'){area.innerHTML=demoHead('把整张相纸，先看一遍','切换纸张，预览照片排列与裁切标记。')+`<div class="demo-card print-demo"><div class="print-paper" id="print-paper"></div><div class="print-controls"><label class="demo-note" for="demo-paper">打印纸张</label><select class="demo-button" id="demo-paper"><option value="six">6 寸相纸</option><option value="a4">A4</option></select><p id="print-count" class="demo-note"></p><label class="demo-note"><input type="checkbox" id="crop-marks"> 裁切标记</label></div></div><p class="demo-note">示例是一寸照片排版示意，不提供可打印尺寸文件。实际 PDF 请在桌面软件中生成。</p>`;const update=()=>{const a4=$('#demo-paper').value==='a4',n=a4?49:10;$('#print-paper').classList.toggle('a4',a4);$('#print-paper').classList.toggle('crop',$('#crop-marks').checked);$('#print-paper').innerHTML=Array.from({length:n},()=>'<div class="portrait"></div>').join('');$('#print-count').textContent=`每页 ${n} 张 · ${a4?'7 × 7':'5 × 2'} 排列`};$('#demo-paper').addEventListener('change',update);$('#crop-marks').addEventListener('change',update);update()}}
function selectDemo(id){activeDemo=id;$$('[data-demo]').forEach(b=>{const on=b.dataset.demo===id;b.classList.toggle('active',on);b.setAttribute('aria-selected',on);b.tabIndex=on?0:-1});renderDemo()}
$('#demo-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-demo]');if(b)selectDemo(b.dataset.demo)});$('#demo-tabs').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();let i=demos.findIndex(d=>d.id===activeDemo);i=e.key==='Home'?0:e.key==='End'?demos.length-1:(i+(e.key==='ArrowRight'?1:-1)+demos.length)%demos.length;selectDemo(demos[i].id);$(`[data-demo="${activeDemo}"]`).focus()});renderDemo();
function parseRange(text,total){const tokens=text.trim().split(/[,，]/);if(!text.trim()||tokens.some(t=>!t.trim()))return{error:'请输入页码范围，例如 1-3, 5-7'};const ranges=[];for(const token of tokens){const m=token.trim().match(/^(\d+)\s*(?:-\s*(\d+))?$/);if(!m)return{error:'范围格式有误，请使用页码或 起始页-结束页'};const a=Number(m[1]),b=m[2]?Number(m[2]):a;if(a<1||b>total||a>b)return{error:`有效页码为 1-${total}，起始页不能大于结束页`};ranges.push([a,b])}return{ranges,count:ranges.reduce((s,[a,b])=>s+b-a+1,0)}}
let selectedFile=null,resultURL=null,inputRevision=0,busy=false;
function sizeLabel(bytes){return bytes>=1024*1024?(bytes/1024/1024).toFixed(2)+' MB':(bytes/1024).toFixed(1)+' KB'}
function clearResult(){inputRevision++;if(resultURL){URL.revokeObjectURL(resultURL);resultURL=null}$('#lab-result').hidden=true;$('#lab-download').removeAttribute('href')}
function chooseFile(file){clearResult();selectedFile=null;$('#compress').disabled=true;if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){$('#lab-status').textContent='请选择 JPG、PNG 或 WebP 图片。';return}if(file.size>20*1024*1024){$('#lab-status').textContent='图片超过 20 MB，请使用桌面软件处理。';return}selectedFile=file;$('#upload-zone strong').textContent=file.name;$('#lab-status').textContent=`已选择 ${file.name} · ${sizeLabel(file.size)}。调整设置后点击处理。`;$('#compress').disabled=busy}
$('#image-file').addEventListener('change',e=>chooseFile(e.target.files[0]));const zone=$('#upload-zone');['dragenter','dragover'].forEach(name=>zone.addEventListener(name,e=>{e.preventDefault();zone.classList.add('dragging')}));['dragleave','drop'].forEach(name=>zone.addEventListener(name,e=>{e.preventDefault();zone.classList.remove('dragging');if(name==='drop'){if(e.dataTransfer.files.length>1){$('#lab-status').textContent='请一次选择一张图片。';return}chooseFile(e.dataTransfer.files[0])}}));
function settingsChanged(){clearResult();const png=$('#output-format').value==='image/png',webp=$('#output-format').value==='image/webp';$('#quality').disabled=png;$('#quality-value').textContent=png?'无损':$('#quality').value+'%';$('#format-hint').textContent=png?'PNG 保留透明背景，质量滑块不适用，体积可能比原图大。':webp?'WebP 支持透明背景，实际输出以浏览器编码能力为准。':'JPG 不支持透明背景，透明区域会填充为白色。';if(selectedFile)$('#lab-status').textContent='参数已更新，请重新处理以生成当前设置的结果。'}
$('#quality').addEventListener('input',settingsChanged);$('#output-format').addEventListener('change',settingsChanged);
$('#compress').addEventListener('click',async()=>{if(!selectedFile||busy)return;clearResult();const revision=inputRevision,file=selectedFile,mime=$('#output-format').value,q=Number($('#quality').value)/100;busy=true;$('#compress').disabled=true;$('#compress').textContent='处理中…';$('#lab-status').textContent='正在浏览器本地处理…';let image=null;try{image=await createImageBitmap(file,{imageOrientation:'from-image'});if(image.width*image.height>36000000||image.width>16000||image.height>16000)throw new Error('图片尺寸过大，请使用桌面软件处理。');const canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('当前浏览器无法创建图片画布。');if(mime==='image/jpeg'){ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height)}ctx.drawImage(image,0,0);const blob=await new Promise(resolve=>canvas.toBlob(resolve,mime,q));if(!blob)throw new Error('图片编码失败，请尝试其他输出格式。');if(blob.type!==mime)throw new Error('当前浏览器不支持所选格式，请改用 JPG 或 PNG。');if(revision!==inputRevision||selectedFile!==file)return;resultURL=URL.createObjectURL(blob);$('#lab-preview').src=resultURL;$('#lab-filename').textContent=file.name;const change=(1-blob.size/file.size)*100;$('#lab-size').textContent=`${sizeLabel(file.size)} → ${sizeLabel(blob.size)} · ${change>=0?'减少 '+change.toFixed(1)+'%':'增加 '+(-change).toFixed(1)+'%'} · ${canvas.width} × ${canvas.height} px`;$('#lab-download').href=resultURL;$('#lab-download').download=file.name.replace(/\.[^.]+$/,'')+'_锐途.'+({'image/jpeg':'jpg','image/webp':'webp','image/png':'png'}[mime]);$('#lab-result').hidden=false;$('#lab-status').textContent=change>=0?'处理完成。检查预览后下载结果。':'处理完成，但体积增加了。可降低质量或选择另一种格式；原图未修改。'}catch(error){if(revision===inputRevision)$('#lab-status').textContent=error.message||'处理失败，请尝试其他图片。'}finally{image?.close();busy=false;$('#compress').disabled=!selectedFile;$('#compress').innerHTML='处理图片 <span>→</span>'}});
